### ISSUE TITLE
Use ExtractTextPlugin to generate a separate css file rather than embedding it via js?

### ISSUE THREAD

**Issue by arjun810** [ankane/frontrunner#1]
It'd be easy to more closely emulate the existing asset pipeline by using ExtractTextPlugin to output a css file, rather than using style-loader to embed the styles via JS. I think it'd ease the transition to webpack. 

Do you agree that'd be worthwhile? If so, I can make a PR.

**Comment by ankane** [comment]
Hey @arjun810, agree that'd it'd ease the transition. Happy to accept a PR 👍

**Comment by ankane** [comment]
Now that Rails supports webpack natively, not much need for this gem.
