### ISSUE TITLE
Is frontrunner helps to resolve_paths between webpack and sprockets?

### ISSUE THREAD

**Issue by bricesanchez** [ankane/frontrunner#2]
Hi @ankane !

First, i would thank you for all your OSS work, it really helps me to ship great apps!

I would like to know if `frontrunner` can help me to use `webpack` along with `sprockets` in `Rails ::Engine` and resolve_paths between `webpack` and `sprockets`?

I'm would like to implement Stimilus.js in `refinerycms` which is a collection of `Rails::Engine`. 

I will have `Stimulus` controllers in `refinerycms-core` and i will need to access them in the main rails app.

**Comment by bricesanchez** [comment]
I found this:

> If you are adding Webpacker to an existing app that has most of the assets inside app/assets or inside an engine, and you want to share that with webpack modules, you can use the resolved_paths option available in config/webpacker.yml. This lets you add additional paths that webpack should lookup when resolving modules:

Source: https://github.com/rails/webpacker#resolved

So adding this in my `config/webpacker.yml` seems to fix my problem:

```yml
[...]
resolved_paths: ['app/assets', 'app/javascripts']
[...]
```

**UPDATE**: It was a false positive. It does not fix my problem

**Comment by ankane** [comment]
Hey @bricesanchez, there’s no reason to use this project anymore.
